### ISSUE TITLE
最近7天无法正常运行

### ISSUE THREAD

**Issue by dll233** [lingsamuel/EpicGamesGiveawaysAutoClaimer#11]
上次成功自动运行是7月31日
之后一直“get gift”报错：
![image](https://user-images.githubusercontent.com/49135636/89901407-9deaf100-dc17-11ea-926a-1a84d1065709.png)

期待您的回复，谢谢！

**Comment by Rhilip** [comment]
同样存在这个问题，我这边是从7月28号起就一直无法正常运行。具体报错我看了下是因为 X display没有被启动起来。

```
2020-07-28 | 08:24:44.696 | ERROR | Error: Failed to launch the browser process!
2889:2889:0728/082444.592542:ERROR:browser\_main\_loop.cc(1512) Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/runner/work/EpicGamesGiveawaysAutoClaimer/EpicGamesGiveawaysAutoClaimer/workdir/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/runner/work/EpicGamesGiveawaysAutoClaimer/EpicGamesGiveawaysAutoClaimer/workdir/node_modules/puppeteer/lib/Launcher.js:740:61)
    at ChildProcess.emit (events.js:327:22)
```

翻看了一下部分分支的Action记录，看起来自8月初，基本大家都没能正常运行获取。

**Comment by lingsamuel** [comment]
大约是 GTA5 开始就不能领了，Epic 貌似改了 API。上游仓库 https://github.com/Revadike/epicgames-freebies-claimer 貌似还没适配，我也没精力去维护它。

**Comment by Rhilip** [comment]
感觉不像是因为这些原因。
GTA5是因为那时候Epic的领取页面做了开启动画，后面GTA5的活动结束后就一直是正常的，也能领取到相关免费游戏。

引一位朋友的运行结果： 
https://github.com/yezi1000/EpicGamesGiveawaysAutoClaimer/blob/0b081a2bddca554d7576593df6c7f148f8ee93e4/games.info#L258-L267

大规模的无法运行应该是从8月起的。

**Comment by dll233** [comment]
@Rhilip 同意您的观点，我也是8月开始无法领取的

**Comment by lingsamuel** [comment]
GTA 之后，我自己运行的结果几乎都是登录失败，捣鼓了一下没有结论，只能认为是 github 的 ip 被 ban 了。

`Unable to open X display` 这个报错的原因是，上游仓库使用的登录库在登录失败时会尝试打开浏览器（puppeteer 下载的 chrome），让用户尝试手动登录。
但是服务器上没有图形界面（X Display），自然就报错了。

所以我感觉还是登录有问题，被 ban 了。

不过奇怪的是你的这个报错信息和我的不大一样：
![image](https://user-images.githubusercontent.com/14567045/90210958-01e10580-de22-11ea-9ce0-addad90281f6.png)

**Comment by lingsamuel** [comment]
这些 bug 可能都是新版本特有的，如果你们真的很闲，可以一个一个版本试验一下。
这个链接可以看到所有的版本哈希（`ref` 的值）https://github.com/Revadike/epicgames-freebies-claimer/commits
我使用的是五月份我的 commit，点击旁边的复制按钮可以复制完整的哈希值：
![image](https://user-images.githubusercontent.com/14567045/90211993-df9cb700-de24-11ea-8cd3-08b46344d5f2.png)

复制下来的哈希值对应这一行：

https://github.com/lingsamuel/EpicGamesGiveawaysAutoClaimer/blob/0cb5c5e2d091f89709967f67801d088ba4a9e22f/.github/workflows/Get_Epic_Game.yml#L31

**Comment by MasterOfStar** [comment]
https://github.com/MasonStooksbury/Free-Games/blob/master/Free_Games.py
也许可以 参考/使用 一下这个？

**Comment by Rhilip** [comment]
> [https://github.com/MasonStooksbury/Free-Games/blob/master/Free_Games.py](https://github.com/MasonStooksbury/Free-Games/blob/master/Free_Games.py?rgh-link-date=2020-12-12T15%3A13%3A49Z)
> 也许可以 参考/使用 一下这个？

没试出来，Github Action没有图形界面，而使用 `sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional` 或者使用 `--headless`强行开的话，我的Action一直处于跑的状态出不来，也算是没有成功运行。

部分错误日志：

```
1608824562546	geckodriver	INFO	Listening on 127.0.0.1:41583
1608824562556	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilemkW9kJ"
Error: no DISPLAY environment variable specified
```

```
1608825045328	geckodriver	INFO	Listening on 127.0.0.1:37337
1608825045337	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofiled8sJd4"
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :99
```

**Comment by MasterOfStar** [comment]
> > [https://github.com/MasonStooksbury/Free-Games/blob/master/Free_Games.py](https://github.com/MasonStooksbury/Free-Games/blob/master/Free_Games.py?rgh-link-date=2020-12-12T15%3A13%3A49Z)
> > 也许可以 参考/使用 一下这个？
> 
> 没试出来，Github Action没有图形界面，而使用 `sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional` 或者使用 `--headless`强行开的话，我的Action一直处于跑的状态出不来，也算是没有成功运行。
> 
> 部分错误日志：
> 
> ```
> 1608824562546	geckodriver	INFO	Listening on 127.0.0.1:41583
> 1608824562556	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilemkW9kJ"
> Error: no DISPLAY environment variable specified
> ```
> 
> ```
> 1608825045328	geckodriver	INFO	Listening on 127.0.0.1:37337
> 1608825045337	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofiled8sJd4"
> Unable to init server: Could not connect: Connection refused
> Error: cannot open display: :99
> ```

我贴的那个不是在github action 跑的... windows本机运行正常... 因为是python，所以放到vps之类的地方应该没有问题
